version: 0.2

phases:
  install:
    commands:
      - cd infrastructure
      - npm install -g aws-cdk
      - npm install
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 358719591151.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Current directory: $(pwd)"
      - ls -la
      - docker build -t learningmap .
      - docker tag learningmap:latest 358719591151.dkr.ecr.us-east-1.amazonaws.com/learningmap:latest
  post_build:
    commands:
      - docker push 358719591151.dkr.ecr.us-east-1.amazonaws.com/learningmap:latest
      - echo Writing image definitions file...
      - printf '[{"name":"learningmap","imageUri":"%s"}]' 358719591151.dkr.ecr.us-east-1.amazonaws.com/learningmap:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json 